#En esta actividad estaré trabjando con un dataset de hongos que tiene el propósito de predecir el tipo de hongo que es (venenoso, no venenoso y no recomendado).

Mushroom [Dataset]. (1981). UCI Machine Learning Repository. https://doi.org/10.24432/C5959T.

##En este documento se hace la limpieza del dataset eliminando columnas que no aportan información al igual que columnas que tengan menos del 70% de sus filas completas.

##Una vez limpio el data set se hace la transformación de las columnas no numéricas mediante dummies (one hot encoding).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Import, según la documentación de UC Irvine

In [ ]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.4.22)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [ ]:
from ucimlrepo import fetch_ucirepo

mushroom = fetch_ucirepo(id=73)

X = mushroom.data.features
y = mushroom.data.targets

print(mushroom.metadata)

print(mushroom.variables)

{'uci_id': 73, 'name': 'Mushroom', 'repository_url': 'https://archive.ics.uci.edu/dataset/73/mushroom', 'data_url': 'https://archive.ics.uci.edu/static/public/73/data.csv', 'abstract': 'From Audobon Society Field Guide; mushrooms described in terms of physical characteristics; classification: poisonous or edible', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 8124, 'num_features': 22, 'feature_types': ['Categorical'], 'demographics': [], 'target_col': ['poisonous'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1981, 'last_updated': 'Thu Aug 10 2023', 'dataset_doi': '10.24432/C5959T', 'creators': [], 'intro_paper': None, 'additional_info': {'summary': "This data set includes descriptions of hypothetical samples corresponding to 23 species of gilled mushrooms in the Agaricus and Lepiota Family (pp. 500-525).  Each species is identified as definitely edible, definitely poisonous, or of unknown edibility and not recommended.  This latter class was combined with the poisonous one.  The Guide clearly states that there is no simple rule for determining the edibility of a mushroom; no rule like ``leaflets three, let it be'' for Poisonous Oak and Ivy.", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '     1. cap-shape:                bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s\r\n     2. cap-surface:              fibrous=f,grooves=g,scaly=y,smooth=s\r\n     3. cap-color:                brown=n,buff=b,cinnamon=c,gray=g,green=r, pink=p,purple=u,red=e,white=w,yellow=y\r\n     4. bruises?:                 bruises=t,no=f\r\n     5. odor:                     almond=a,anise=l,creosote=c,fishy=y,foul=f, musty=m,none=n,pungent=p,spicy=s\r\n     6. gill-attachment:          attached=a,descending=d,free=f,notched=n\r\n     7. gill-spacing:             close=c,crowded=w,distant=d\r\n     8. gill-size:                broad=b,narrow=n\r\n     9. gill-color:               black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e, white=w,yellow=y\r\n    10. stalk-shape:              enlarging=e,tapering=t\r\n    11. stalk-root:               bulbous=b,club=c,cup=u,equal=e, rhizomorphs=z,rooted=r,missing=?\r\n    12. stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s\r\n    13. stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s\r\n    14. stalk-color-above-ring:   brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y\r\n    15. stalk-color-below-ring:   brown=n,buff=b,cinnamon=c,gray=g,orange=o, pink=p,red=e,white=w,yellow=y\r\n    16. veil-type:                partial=p,universal=u\r\n    17. veil-color:               brown=n,orange=o,white=w,yellow=y\r\n    18. ring-number:              none=n,one=o,two=t\r\n    19. ring-type:                cobwebby=c,evanescent=e,flaring=f,large=l, none=n,pendant=p,sheathing=s,zone=z\r\n    20. spore-print-color:        black=k,brown=n,buff=b,chocolate=h,green=r, orange=o,purple=u,white=w,yellow=y\r\n    21. population:               abundant=a,clustered=c,numerous=n, scattered=s,several=v,solitary=y\r\n    22. habitat:                  grasses=g,leaves=l,meadows=m,paths=p, urban=u,waste=w,woods=d', 'citation': None}}
                        name     role         type demographic  \
0                  poisonous   Target  Categorical        None
1                  cap-shape  Feature  Categorical        None
2                cap-surface  Feature  Categorical        None
3                  cap-color  Feature       Binary        None
4                    bruises  Feature  Categorical        None
5                       odor  Feature  Categorical        None
6            gill-attachment  Feature  Categorical        None
7               gill-spacing  Feature  Categorical        None
8                  gill-size  Feature  Categorical        None
9                 gill-color  Feature  Categorical        None
10               stalk-shape  Feature  Categorical        None
11                stalk-root  Feature  Categorical        None
12  stalk-surface-above-ring  Feature  Categorical        None
13  stalk-surface-below-ring  Feature  Categorical        None
14    stalk-color-above-ring  Feature  Categorical        None
15    stalk-color-below-ring  Feature  Categorical        None
16                 veil-type  Feature       Binary        None
17                veil-color  Feature  Categorical        None
18               ring-number  Feature  Categorical        None
19                 ring-type  Feature  Categorical        None
20         spore-print-color  Feature  Categorical        None
21                population  Feature  Categorical        None
22                   habitat  Feature  Categorical        None

                                          description units missing_values
0                                                None  None             no
1   bell=b,conical=c,convex=x,flat=f, knobbed=k,su...  None             no
2                fibrous=f,grooves=g,scaly=y,smooth=s  None             no
3   brown=n,buff=b,cinnamon=c,gray=g,green=r, pink...  None             no
4                                      bruises=t,no=f  None             no
5   almond=a,anise=l,creosote=c,fishy=y,foul=f, mu...  None             no
6            attached=a,descending=d,free=f,notched=n  None             no
7                         close=c,crowded=w,distant=d  None             no
8                                    broad=b,narrow=n  None             no
9   black=k,brown=n,buff=b,chocolate=h,gray=g, gre...  None             no
10                             enlarging=e,tapering=t  None             no
11  bulbous=b,club=c,cup=u,equal=e, rhizomorphs=z,...  None            yes
12                 fibrous=f,scaly=y,silky=k,smooth=s  None             no
13                 fibrous=f,scaly=y,silky=k,smooth=s  None             no
14  brown=n,buff=b,cinnamon=c,gray=g,orange=o, pin...  None             no
15  brown=n,buff=b,cinnamon=c,gray=g,orange=o, pin...  None             no
16                              partial=p,universal=u  None             no
17                  brown=n,orange=o,white=w,yellow=y  None             no
18                                 none=n,one=o,two=t  None             no
19  cobwebby=c,evanescent=e,flaring=f,large=l, non...  None             no
20  black=k,brown=n,buff=b,chocolate=h,green=r, or...  None             no
21  abundant=a,clustered=c,numerous=n, scattered=s...  None             no
22  grasses=g,leaves=l,meadows=m,paths=p, urban=u,...  None             no

#Nota: Menciona que hay missing values en el feature 11 "stalk root" y nos dice que cap-color y veil-type son binarias

Modificar la importación para manejarlo como pandas: ¿por qué? poruqe estoy más familiarizado y me gusta para analizar los datos

In [ ]:
#pasar a pandas
X = pd.DataFrame(mushroom.data.features)
y = pd.DataFrame(mushroom.data.targets)

# estoy juntando el target con el resto de datos en una tabla (más adelante se vuelven a separar)
df = pd.concat([X, y], axis=1)

print(df.head())

  cap-shape cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0         x           s         n       t    p               f            c
1         x           s         y       t    a               f            c
2         b           s         w       t    l               f            c
3         x           y         w       t    p               f            c
4         x           s         g       f    n               f            w

  gill-size gill-color stalk-shape  ... stalk-color-above-ring  \
0         n          k           e  ...                      w
1         b          k           e  ...                      w
2         b          n           e  ...                      w
3         n          n           e  ...                      w
4         b          k           t  ...                      w

  stalk-color-below-ring veil-type veil-color ring-number ring-type  \
0                      w         p          w           o         p
1                      w         p          w           o         p
2                      w         p          w           o         p
3                      w         p          w           o         p
4                      w         p          w           o         e

  spore-print-color population habitat poisonous
0                 k          s       u         p
1                 n          n       g         e
2                 n          n       m         e
3                 k          s       u         p
4                 n          a       g         e

[5 rows x 23 columns]

Me da 23 columnas, sin embargo solo hay 22 features, agregó una columna de id, la cual no es del data frame.

In [ ]:
df.shape

(8124, 23)

In [ ]:
df.describe()

,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,stalk-shape,...,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat,poisonous
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,6,4,10,2,9,2,2,2,12,2,...,9,9,1,4,3,5,9,6,7,2
top,x,y,n,f,n,f,c,b,b,t,...,w,w,p,w,o,p,w,v,d,e
freq,3656,3244,2284,4748,3528,7914,6812,5612,1728,4608,...,4464,4384,8124,7924,7488,3968,2388,4040,3148,4208

A continuación traspongo la tabla previa para que me muestre la tabla completa

In [ ]:
df.describe(include='all').T

                         count unique top  freq
cap-shape                 8124      6   x  3656
cap-surface               8124      4   y  3244
cap-color                 8124     10   n  2284
bruises                   8124      2   f  4748
odor                      8124      9   n  3528
gill-attachment           8124      2   f  7914
gill-spacing              8124      2   c  6812
gill-size                 8124      2   b  5612
gill-color                8124     12   b  1728
stalk-shape               8124      2   t  4608
stalk-root                5644      4   b  3776
stalk-surface-above-ring  8124      4   s  5176
stalk-surface-below-ring  8124      4   s  4936
stalk-color-above-ring    8124      9   w  4464
stalk-color-below-ring    8124      9   w  4384
veil-type                 8124      1   p  8124
veil-color                8124      4   w  7924
ring-number               8124      3   o  7488
ring-type                 8124      5   p  3968
spore-print-color         8124      9   w  2388
population                8124      6   v  4040
habitat                   8124      7   d  3148
poisonous                 8124      2   e  4208

#Vemos nuevamente que el stalk-root está incompleto. Necesito revisar qué significa para decidir si eliminarlo o no.

#Además, aquí encuentro una variable "veil-type", la cual solo tiene 1 unique value. Es decir que toda la columna es lo mismo y por lo mismo puede eliminarse.

De igual forma hay otras columnas donde una sola variable componen la mayoría de las filas, sin embargo estas sí pueden aportar información para determinar entre una clase y otra.

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   cap-shape                 8124 non-null   object
 1   cap-surface               8124 non-null   object
 2   cap-color                 8124 non-null   object
 3   bruises                   8124 non-null   object
 4   odor                      8124 non-null   object
 5   gill-attachment           8124 non-null   object
 6   gill-spacing              8124 non-null   object
 7   gill-size                 8124 non-null   object
 8   gill-color                8124 non-null   object
 9   stalk-shape               8124 non-null   object
 10  stalk-root                5644 non-null   object
 11  stalk-surface-above-ring  8124 non-null   object
 12  stalk-surface-below-ring  8124 non-null   object
 13  stalk-color-above-ring    8124 non-null   object
 14  stalk-color-below-ring    8124 non-null   object
 15  veil-type                 8124 non-null   object
 16  veil-color                8124 non-null   object
 17  ring-number               8124 non-null   object
 18  ring-type                 8124 non-null   object
 19  spore-print-color         8124 non-null   object
 20  population                8124 non-null   object
 21  habitat                   8124 non-null   object
 22  poisonous                 8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB
None

#Todos los datatypes se cambiaron a object (es bueno que toda la columna tenga el mismo tipo). En este dataset, no hay datos numéricos, solo clasificativos.

#Limpieza de datos

Eliminar datos basura y rellenar valores necesarios.

In [ ]:
conteo_no_nulos = df.count().sort_values(ascending=False)
total_filas = len(df)

resumen_completitud = pd.DataFrame({
    "No_nulos": conteo_no_nulos,
    "Total_filas": total_filas,
    "Porcentaje_completitud (%)": round(conteo_no_nulos / total_filas * 100, 2)
})

resumen_completitud = resumen_completitud.sort_values(by="Porcentaje_completitud (%)", ascending=False)

print("Resumen de completitud de columnas:")
display(resumen_completitud)

umbral = 70
columnas_bajas = resumen_completitud[resumen_completitud["Porcentaje_completitud (%)"] < umbral]
if not columnas_bajas.empty:
    print(f"\n Columnas con menos del {umbral}% de completitud:")
    display(columnas_bajas)
else:
    print(f"\nTodas las columnas tienen al menos {umbral}% de completitud.")

Resumen de completitud de columnas:

                          No_nulos  Total_filas  Porcentaje_completitud (%)
cap-shape                     8124         8124                      100.00
cap-surface                   8124         8124                      100.00
cap-color                     8124         8124                      100.00
bruises                       8124         8124                      100.00
odor                          8124         8124                      100.00
gill-attachment               8124         8124                      100.00
gill-spacing                  8124         8124                      100.00
gill-size                     8124         8124                      100.00
gill-color                    8124         8124                      100.00
stalk-shape                   8124         8124                      100.00
stalk-surface-above-ring      8124         8124                      100.00
stalk-color-above-ring        8124         8124                      100.00
stalk-surface-below-ring      8124         8124                      100.00
stalk-color-below-ring        8124         8124                      100.00
veil-type                     8124         8124                      100.00
spore-print-color             8124         8124                      100.00
veil-color                    8124         8124                      100.00
ring-number                   8124         8124                      100.00
ring-type                     8124         8124                      100.00
habitat                       8124         8124                      100.00
population                    8124         8124                      100.00
poisonous                     8124         8124                      100.00
stalk-root                    5644         8124                       69.47

 Columnas con menos del 70% de completitud:

            No_nulos  Total_filas  Porcentaje_completitud (%)
stalk-root      5644         8124                       69.47

#Como ya sabíamos, stalk root está incompleto. Sin embargo está en casi un 70% de los registros por lo que probablemente decida manejar dos sets de datos. Uno sin la columna y otro sin las filas incompletas para ver qué resultado es mejor. Por ahora, solo generaré el que elimina la columna por completo

##limpieza de columnas

In [ ]:
df.shape

(8124, 23)

In [ ]:
# Lista de columnas a eliminar
columnas_a_eliminar = [
    "stalk-root",
    "veil-type"
]

# Eliminar las columnas (si existen)
df_limpio = df.drop(columns=[col for col in columnas_a_eliminar if col in df.columns])

print("Columnas eliminadas correctamente.")

df_limpio.shape

Columnas eliminadas correctamente.

(8124, 21)

#Eliminé la columna incompleta únicamente en df_limpio

##Identificar valores únicos

El siguiente código es medio redundante porque describe() ya me dice los valores únicos de las columnas, pero me deja las columnas organizadas de menor variabilidad a mayor así que igual lo voy a dejar.

Cuanto menos me ayuda a ver que 6 de las columnas pueden ser binarias

In [ ]:
valores_unicos = df_limpio.nunique().sort_values()

resumen_unicos = pd.DataFrame({
    "Valores_únicos": valores_unicos,
    "Total_filas": len(df_limpio),
    "Porcentaje_únicos (%)": round(valores_unicos / len(df_limpio) * 100, 3)
})

# Mostrar de menor a mayor (columnas menos variables primero)
print("Cantidad de valores únicos por columna:")
display(resumen_unicos)

# === (Opcional) Mostrar solo columnas con muy poca variabilidad ===
umbral_unicos = 2  # por ejemplo, columnas con solo 1 o 2 valores únicos
columnas_poco_utiles = resumen_unicos[resumen_unicos["Valores_únicos"] <= umbral_unicos]

if not columnas_poco_utiles.empty:
    print(f"\n !!!!!!!!!!!!! Columnas con {umbral_unicos} o menos valores únicos:")
    display(columnas_poco_utiles)
else:
    print(f"\n Todas las columnas tienen más de {umbral_unicos} valores únicos.")

Cantidad de valores únicos por columna:

                          Valores_únicos  Total_filas  Porcentaje_únicos (%)
bruises                                2         8124                  0.025
gill-size                              2         8124                  0.025
gill-spacing                           2         8124                  0.025
gill-attachment                        2         8124                  0.025
stalk-shape                            2         8124                  0.025
poisonous                              2         8124                  0.025
ring-number                            3         8124                  0.037
cap-surface                            4         8124                  0.049
veil-color                             4         8124                  0.049
stalk-surface-above-ring               4         8124                  0.049
stalk-surface-below-ring               4         8124                  0.049
ring-type                              5         8124                  0.062
cap-shape                              6         8124                  0.074
population                             6         8124                  0.074
habitat                                7         8124                  0.086
odor                                   9         8124                  0.111
spore-print-color                      9         8124                  0.111
stalk-color-above-ring                 9         8124                  0.111
stalk-color-below-ring                 9         8124                  0.111
cap-color                             10         8124                  0.123
gill-color                            12         8124                  0.148

 !!!!!!!!!!!!! Columnas con 2 o menos valores únicos:

                 Valores_únicos  Total_filas  Porcentaje_únicos (%)
bruises                       2         8124                  0.025
gill-size                     2         8124                  0.025
gill-spacing                  2         8124                  0.025
gill-attachment               2         8124                  0.025
stalk-shape                   2         8124                  0.025
poisonous                     2         8124                  0.025

# En el siguiente código con dropna, se eliminan las filas con valores vacios. En este caso solo serían las de stalk root, pero eliminé la columna

In [ ]:
filas_antes = len(df_limpio)

df_limpio = df_limpio.dropna()

filas_despues = len(df_limpio)
filas_eliminadas = filas_antes - filas_despues

print(f" Se eliminaron {filas_eliminadas} filas con datos vacíos.")
print(f" Total antes: {filas_antes} → Total después: {filas_despues}")

df_limpio.to_excel("/content/datosHongosLimpios.xlsx", index=False)
print("Archivo final guardado como 'datosHongosLimpios.xlsx'")

 Se eliminaron 0 filas con datos vacíos.
 Total antes: 8124 → Total después: 8124
Archivo final guardado como 'datosHongosLimpios.xlsx'

In [ ]:
df_limpio.shape

(8124, 21)

#Separación de dataset en train y test

In [ ]:
from sklearn.model_selection import train_test_split
#Ahora sí separamos los datos
X = df_limpio.drop("poisonous", axis=1)
y = df_limpio["poisonous"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,

    #permite mantener proporciones de y (poisonous) en la separación
    stratify=y
)

#Tratamiento de datos

Código para agregar algunas columnas que pueden servir para el análisis y cambio en los formatos de datos.

Para este problema seguramente sea necesario hacer un one hot encoding

##Escalamiento (one hot encoding)

In [ ]:
X_train_encoded = pd.get_dummies(X_train)
X_test_encoded = pd.get_dummies(X_test)


print(X_train_encoded.shape)
print(X_test_encoded.shape)

(6499, 111)
(1625, 110)

Ambas columnas deberían ser iguales, por ello hay que alinearlas, ya que si no no se puede predecir.

Lo que hacemos es si en test hay (azul/amarillo) y en train hay (azul/rojo), vamos a tener en ambos (azul/amarillo/rojo)

In [ ]:
# Hacer que las columnas coincidan entre train y test
X_train_encoded, X_test_encoded = X_train_encoded.align(
    X_test_encoded,
    join='left',
    axis=1,
    fill_value=0
)

print(X_train_encoded.shape)
print(X_test_encoded.shape)

(6499, 111)
(1625, 111)

In [ ]:
X_train_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6499 entries, 5249 to 2411
Columns: 111 entries, cap-shape_b to habitat_w
dtypes: bool(111)
memory usage: 755.3 KB

In [ ]:
X_train_encoded.describe(include='all').T

            count unique    top  freq
cap-shape_b  6499      2  False  6138
cap-shape_c  6499      2  False  6495
cap-shape_f  6499      2  False  3982
cap-shape_k  6499      2  False  5846
cap-shape_s  6499      2  False  6472
...           ...    ...    ...   ...
habitat_l    6499      2  False  5839
habitat_m    6499      2  False  6268
habitat_p    6499      2  False  5608
habitat_u    6499      2  False  6198
habitat_w    6499      2  False  6342

[111 rows x 4 columns]